name: thesis
channels:
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - pip
  - pip:
      - gymnasium[other]
      - gymnasium==1.1.1
      - highway-env==1.10.1
      - neptune-tensorboard==1.0.3
      - neptune==1.13.0
      - numpy==2.1.3
      - stable_baselines3[extra]
      - stable_baselines3==2.6.0
      - torch==2.6.0
variables:
  NEPTUNE_API_TOKEN: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIxNmNhNWRkYS01YzQ5LTRkOWUtYjQ2Yy01ZmE0NTY2YWIwMDQifQ=="
  NEPTUNE_PROJECT: "peter-v./thesis"